### PR TITLE
TLS 1.1 connection rejected.

### PR DESCRIPTION
**Pull request by hinsona**
Force TLS 1.2 to avoid issues where the connection is rejected due to TLS 1.1 being used.

### CODE REVIEW

**Comment by f1ana** [comment]
Hello, I do not believe that this behavior should live in this library, or any other for that matter.  IMO, this should be set by the calling application on startup.

**Comment by hinsona** [comment]
Hello Chris,

If the library abstracts the connection it’s not clear that it’s necessary.
I only discovered the issue existed after troubleshooting HTTPS connection
rejections. If the Nominatim servers are rejecting TLS 1.1, it’s necessary.
Perhaps it’s something for the docs?

Thanks for reading.

**Comment by f1ana** [comment]
Hello,

What I mean to say is that, the configuration for ServicePointManager is global, no matter where it is being called from.  This _could_ have an adverse effect on applications that do need to rely on older methods (e.g.  legacy systems, etc.).
Such a configuration should be opt-in by the developer.  With that said, I think that we can add something in the readme to state that TLS 1.2+ is the way to go for accessing Nominatim.

Thanks,
Chris

**Comment by hinsona** [comment]
Hello Chris,

Understood. Noting it the readme would be adequate. Thank you!

Andrew

**Pull request closed without merging**
